.travis.yml

This will create a new release on Github and upload the assembly jar. However, a dev / maintainer
should update the release doc with recent changes manually.

Release to Github releases when there is a tag push

---

README.md

The end-to-end testing was done using the [exasol/compatibility-test-suite](https://github.com/exasol/compatibility-test-suite) scripts.
- basic type checks
- column size limit checks
- utf8 checks 
The `nullable checks` are not possible since it is not possible to determine the nullability of a column via `ExaMetadata` and `ExaIterator` yet.
Similarly updated the Readme with new export SQL commands.

Release of GCS and Azure export feature

---

project/Dependencies.scala
src/main/scala/com/exasol/cloudetl/bucket/AzureAdlsBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/AzureBlobBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/main/scala/com/exasol/cloudetl/source/Source.scala
src/test/scala/com/exasol/cloudetl/bucket/BucketSuite.scala

Add support for Azure Data Lake (Gen1) Storage

---

README.md
docs/overview.md
src/main/resources/log4j.properties
src/main/scala/com/exasol/cloudetl/bucket/AzureAdlsBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/AzureBlobBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/main/scala/com/exasol/cloudetl/bucket/GCSBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/LocalBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/S3Bucket.scala
src/main/scala/com/exasol/cloudetl/data/Row.scala
src/main/scala/com/exasol/cloudetl/parquet/ParquetWriteOptions.scala
src/main/scala/com/exasol/cloudetl/parquet/RowWriteSupport.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/ExportPath.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/ExportTable.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/ImportFiles.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/ImportMetadata.scala
src/main/scala/com/exasol/cloudetl/source/ParquetSource.scala
src/test/scala/com/exasol/cloudetl/bucket/BucketSuite.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/ExportPathSuite.scala

- Scaladoc comments and documentation improvements.
- Improve export parallelism using `iproc()`
- Add additional parameters such as compression codec.

Some refactorings after debugging session

---

src/main/scala/com/exasol/cloudetl/orc/OrcDeserializer.scala
src/test/scala/com/exasol/cloudetl/orc/OrcDeserializerTest.scala

Fix bug ORC decimal import should be java.math.BigDecimal.

---

CHANGES.md
README.md
docs/developer_guide.md
project/Dependencies.scala
project/build.properties
project/plugins.sbt
sbtx

Add list of dependencies with licences to Readme.

---

CHANGES.md
docs/storage/cloud_storages.md
src/main/scala/com/exasol/cloudetl/bucket/AzureAbfsBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/AzureBlobBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/main/scala/com/exasol/cloudetl/source/Source.scala
src/test/scala/com/exasol/cloudetl/bucket/AzureAbfsBucketTest.scala

Adds Azure Datalake Gen2 Storage Support

---

docs/developer_guide.md
project/Dependencies.scala
project/plugins.sbt
project/project/plugins.sbt
scripts/ci.sh

#70: updated dependencies to make the project run with IntelliJ IDEA

---

docs/system_requirements.md

#72: added initial version of system_requirements.md

---

docs/user_guide.md

Propose to add an example of the IMPORT command using Connections into a user_guide file, as suggested by the #66.

Addressing topic #66 - added an example into a User Guide

---

.travis.yml
AUTHORS.md
README.md
doc/changes/changelog.md
doc/changes/changes_0.8.0.md
doc/changes/changes_0.9.0.md

#100: Renamed the repository

---

doc/changes/changes_0.9.0.md
project/Dependencies.scala
src/main/scala/com/exasol/cloudetl/bucket/AzureAbfsBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/AzureBlobBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/BucketValidationException.scala
src/main/scala/com/exasol/cloudetl/bucket/SecureBucket.scala
src/test/scala/com/exasol/cloudetl/bucket/AbstractBucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/AzureAbfsBucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/AzureAdlsBucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/AzureBlobBucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/S3BucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/SecureBucketTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/PathTest.scala

#103: Removed credentials from user provided parameters

---

doc/changes/changelog.md
doc/changes/changes_0.9.1.md
doc/user_guide/user_guide.md
project/Dependencies.scala

#89: Increased the default bucket path name characters

---

.gitignore
doc/changes/changes_0.9.1.md
project/Dependencies.scala
src/main/scala/com/exasol/cloudetl/parquet/RowReadSupport.scala
src/main/scala/com/exasol/cloudetl/parquet/RowWriteSupport.scala
src/main/scala/com/exasol/cloudetl/util/SchemaUtil.scala
src/test/scala/com/exasol/cloudetl/util/SchemaUtilTest.scala

Updated the parquet-hadoop version from 1.10.1 to 1.11.1

---

doc/changes/changes_0.9.1.md
doc/user_guide/user_guide.md
project/Dependencies.scala
src/main/scala/com/exasol/cloudetl/parquet/converter/ConverterFactory.scala
src/main/scala/com/exasol/cloudetl/parquet/converter/ParquetConverter.scala
src/main/scala/com/exasol/cloudetl/parquet/converter/ParquetRootConverter.scala
src/main/scala/com/exasol/cloudetl/parquet/converter/ValueHolder.scala
src/test/scala/com/exasol/cloudetl/parquet/BaseParquetReaderTest.scala
src/test/scala/com/exasol/cloudetl/parquet/ParquetRowReaderComplexTypesTest.scala
src/test/scala/com/exasol/cloudetl/parquet/ParquetRowReaderPrimitiveTypesTest.scala
src/test/scala/com/exasol/cloudetl/parquet/ParquetRowReaderTest.scala
src/test/scala/com/exasol/cloudetl/parquet/converter/ParquetConverterTest.scala
src/test/scala/com/exasol/cloudetl/parquet/converter/ValueHolderTest.scala

Added support for importing Parquet complex types

---

doc/changes/changes_1.0.0.md
src/it/scala/com/exasol/cloudetl/BaseIntegrationTest.scala
src/it/scala/com/exasol/cloudetl/DataImporterIT.scala
src/it/scala/com/exasol/cloudetl/FilesMetadataReaderIT.scala
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/main/scala/com/exasol/cloudetl/filesystem/FileSystemManager.scala
src/main/scala/com/exasol/cloudetl/filesystem/HiddenFilesFilter.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/ImportMetadata.scala
src/test/scala/com/exasol/cloudetl/filesystem/FileSystemManagerTest.scala
src/test/scala/com/exasol/cloudetl/source/AbstractSourceTest.scala
src/test/scala/com/exasol/cloudetl/source/ParquetSourceTest.scala

#35: Ignore hidden and metadata files

---

doc/user_guide/user_guide.md

Explicitly mention ACCESS privilege on connection as a prerequisite.
Fixes #131.

Document the need for ACCESS privilege (#131)

---

.travis.yml
build.sbt
doc/changes/changelog.md
doc/changes/changes_1.1.0.md
doc/changes/changes_1.2.0.md
doc/user_guide/user_guide.md
project/Dependencies.scala
project/plugins.sbt
project/project/plugins.sbt
src/it/scala/com/exasol/cloudetl/BaseIntegrationTest.scala
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/main/scala/com/exasol/cloudetl/bucket/HDFSBucket.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/DockerTableDataExporter.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/DockerTableExportQueryGenerator.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/TableDataExporter.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/TableExportQueryGenerator.scala
src/test/scala/com/exasol/cloudetl/bucket/HDFSBucketTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/TableDataExporterTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/TableExportQueryGeneratorTest.scala

#134: Added support for HDFS

---

.github/workflows/github_release.yml
.github/workflows/prepare_original_checksum.yml
.github/workflows/print_quick_checksum.yml
build.sbt
doc/changes/changes_1.1.0.md
project/plugins.sbt
src/main/scala/com/exasol/cloudetl/parquet/converter/ParquetConverter.scala
src/test/scala/com/exasol/cloudetl/parquet/ParquetRowReaderPrimitiveTypesTest.scala

#137: Fixed Parquet dictionary encoded decimal converter bug

---

.travis.yml
README.md
doc/changes/changes_1.1.0.md
doc/user_guide/user_guide.md
project/Dependencies.scala
project/Settings.scala
src/it/scala/com/exasol/cloudetl/AlluxioExportImportIT.scala
src/it/scala/com/exasol/cloudetl/BaseIntegrationTest.scala
src/it/scala/com/exasol/cloudetl/BaseS3IntegrationTest.scala
src/it/scala/com/exasol/cloudetl/DataImporterIT.scala
src/it/scala/com/exasol/cloudetl/DockerNamedNetwork.scala
src/it/scala/com/exasol/cloudetl/FilesMetadataReaderIT.scala
src/main/scala/com/exasol/cloudetl/bucket/AlluxioBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/DockerFilesDataImporter.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/DockerFilesImportQueryGenerator.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/DockerFilesMetadataReader.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/DockerTableDataExporter.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/DockerTableExportQueryGenerator.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/ExportPath.scala
src/test/scala/com/exasol/cloudetl/bucket/AlluxioBucketTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/ExportPathTest.scala

#135: Added Alluxio filesystem support

---

README.md
doc/changes/changes_1.1.1.md

#141: Updated readme with recent changes

---

.github/workflows/broken_link_checker.yml
doc/changes/changes_1.1.1.md

#143: Added broken links checker Github actions workflow

---

doc/changes/changes_1.1.1.md
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/main/scala/com/exasol/cloudetl/filesystem/FileSystemManager.scala
src/test/scala/com/exasol/cloudetl/filesystem/FileSystemManagerTest.scala
src/test/scala/com/exasol/cloudetl/source/AbstractSourceTest.scala
src/test/scala/com/exasol/cloudetl/source/ParquetSourceTest.scala

#146: Fixed bug with getting files from a path without asterisk

---

doc/changes/changes_1.2.0.md
doc/user_guide/user_guide.md

#151: Updated userguide overview

---

.github/workflows/ci-build.yml
build.sbt
doc/changes/changes_1.2.1.md
project/Dependencies.scala
project/Settings.scala
project/plugins.sbt
src/main/resources/log4j.properties

#156: Fixed logging backend bug

---

doc/changes/changes_1.2.1.md
project/Dependencies.scala
project/plugins.sbt
src/main/scala/com/exasol/cloudetl/parquet/RowWriteSupport.scala
src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
src/main/scala/com/exasol/cloudetl/util/DateTimeUtil.scala

#162: Fixed sonar code smells

---

doc/changes/changes_1.3.0.md
src/it/scala/com/exasol/cloudetl/BaseDataImporterIT.scala
src/it/scala/com/exasol/cloudetl/BaseS3IntegrationTest.scala
src/it/scala/com/exasol/cloudetl/export/DataExporterIT.scala
src/main/scala/com/exasol/cloudetl/helper/ExasolColumnValueProvider.scala
src/main/scala/com/exasol/cloudetl/parquet/RowWriteSupport.scala
src/test/scala/com/exasol/cloudetl/helper/ExasolColumnValueProviderTest.scala

#166: Fixed bug on exporting decimals without trailing zeros

---

doc/user_guide/user_guide.md
src/main/scala/com/exasol/cloudetl/bucket/GCSBucket.scala
src/main/scala/com/exasol/cloudetl/bucket/S3Bucket.scala
src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
src/test/scala/com/exasol/cloudetl/bucket/GCSBucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/S3BucketTest.scala

Use the available functionality in hdfs storage implementations for GCP and S3

Add support for connections behind from behind proxy

---

doc/changes/changelog.md
doc/changes/changes_2.1.1.md
project/Dependencies.scala

#178: Updated log4j version to 2.17.0

---

src/main/scala/com/exasol/cloudetl/bucket/S3Bucket.scala
src/test/scala/com/exasol/cloudetl/bucket/S3BucketTest.scala

#184: Added parameter to ssl enabled

---

build.sbt
doc/changes/changes_2.3.0.md
doc/user_guide/user_guide.md
project/Dependencies.scala
scripts/ci.sh
src/it/scala/com/exasol/cloudetl/parquet/ParquetDataImporterIT.scala
src/main/scala/com/exasol/cloudetl/helper/UUIDConverter.scala
src/main/scala/com/exasol/cloudetl/parquet/ParquetValueConverter.scala
src/test/scala/com/exasol/cloudetl/parquet/ParquetRowReaderPrimitiveTypesTest.scala

#183: Added support for Parquet UUID type

---

doc/changes/changes_2.3.1.md
src/main/scala/com/exasol/cloudetl/bucket/S3Bucket.scala
src/test/scala/com/exasol/cloudetl/bucket/S3BucketTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/PathTest.scala

#190: Added validation for S3 buckets that end with a number

---

doc/changes/changes_2.3.1.md
doc/user_guide/user_guide.md
pom.xml
src/main/scala/com/exasol/cloudetl/emitter/FilesDataEmitter.scala
src/main/scala/com/exasol/cloudetl/helper/DateTimeConverter.scala
src/main/scala/com/exasol/cloudetl/orc/converter/OrcConverter.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/TableDataExporter.scala
src/main/scala/com/exasol/cloudetl/sink/BatchSizedSink.scala
src/test/scala/com/exasol/cloudetl/avro/AvroTestDataWriter.scala
src/test/scala/com/exasol/cloudetl/bucket/AbstractBucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/SecureBucketTest.scala
src/test/scala/com/exasol/cloudetl/helper/DateTimeConverterTest.scala
src/test/scala/com/exasol/cloudetl/helper/ExasolColumnValueProviderTest.scala
src/test/scala/com/exasol/cloudetl/it/avro/AvroDataImporterIT.scala
src/test/scala/com/exasol/cloudetl/it/export/DataExporterIT.scala
src/test/scala/com/exasol/cloudetl/it/orc/OrcDataImporterIT.scala
src/test/scala/com/exasol/cloudetl/it/parquet/ParquetDataImporterIT.scala
src/test/scala/com/exasol/cloudetl/it/timestamp/TimestampWithUTCImportExportIT.scala
src/test/scala/com/exasol/cloudetl/orc/OrcTestDataWriter.scala
src/test/scala/com/exasol/cloudetl/orc/converter/BaseOrcConverterTest.scala
src/test/scala/com/exasol/cloudetl/orc/converter/OrcConverterComplexTypesTest.scala
src/test/scala/com/exasol/cloudetl/orc/converter/OrcConverterPrimitiveTypesTest.scala
src/test/scala/com/exasol/cloudetl/parquet/ParquetSourceTest.scala
src/test/scala/com/exasol/cloudetl/parquet/ParquetTestDataWriter.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/PathTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/TableDataExporterTest.scala

#194: Added support for `UTC` timezone parameter

---

.github/workflows/ci-build.yml
dependencies.md
doc/changes/changes_2.3.1.md
pom.xml
src/test/scala/com/exasol/cloudetl/it/BaseS3IntegrationTest.scala

#195: Fixed bug with Azure Data Lake Gen2 missing class

---

doc/changes/changelog.md
doc/changes/changes_2.4.0.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/main/scala/com/exasol/cloudetl/helper/ExportParallelismCalculator.scala
src/main/scala/com/exasol/cloudetl/parallelism/AbstractUdfCountCalculator.scala
src/main/scala/com/exasol/cloudetl/parallelism/UdfCountCalculator.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/FilesImportQueryGenerator.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/FilesMetadataReader.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/TableExportQueryGenerator.scala
src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
src/test/scala/com/exasol/cloudetl/helper/ExasolColumnValueProviderTest.scala
src/test/scala/com/exasol/cloudetl/helper/ExportParallelismCalculatorTest.scala
src/test/scala/com/exasol/cloudetl/it/BaseS3IntegrationTest.scala
src/test/scala/com/exasol/cloudetl/it/scriptclasses/ExportParallelismIT.scala
src/test/scala/com/exasol/cloudetl/it/scriptclasses/FilesMetadataReaderIT.scala
src/test/scala/com/exasol/cloudetl/parallelism/AbstractUdfCountCalculatorTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/FilesImportQueryGeneratorTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/FilesMetadataReaderTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/TableExportQueryGeneratorTest.scala
src/test/scala/com/exasol/cloudetl/storage/StoragePropertiesTest.scala

#209: Added auto parallelism support

---

dependencies.md
doc/changes/changelog.md
doc/changes/changes_2.4.1.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/test/scala/com/exasol/cloudetl/bucket/AbstractBucketTest.scala
src/test/scala/com/exasol/cloudetl/bucket/BucketContractTest.scala
src/test/scala/com/exasol/cloudetl/source/SourceContractTest.scala

#205: Fixed missing Sonar coverage badge

---

.github/workflows/ci-build.yml
.github/workflows/release_droid_upload_github_release_assets.yml
.scalafmt.conf
dependencies.md
doc/changes/changes_2.4.1.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/main/scala/com/exasol/cloudetl/helper/ParquetSchemaConverter.scala
src/main/scala/com/exasol/cloudetl/parquet/ParquetValueConverter.scala
src/test/scala/com/exasol/cloudetl/it/BaseIntegrationTest.scala

#214: Updated build instructions in user guide

---

dependencies.md
doc/changes/changelog.md
doc/changes/changes_2.6.1.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/test/java/com/exasol/cloudetl/extension/ExtensionIT.java

#229: Fixed vulnerabilities

---

.github/workflows/broken_links_checker.yml
.github/workflows/ci-build.yml
.project-keeper.yml
.scalafmt.conf
dependencies.md
doc/changes/changelog.md
doc/changes/changes_2.6.2.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
src/test/java/com/exasol/cloudetl/extension/ExtensionIT.java
src/test/scala/com/exasol/cloudetl/bucket/DeltaFormatBucketTest.scala
src/test/scala/com/exasol/cloudetl/it/delta/DeltaDataImporterIT.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/FilesDataImporterTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/StorageTest.scala
src/test/scala/com/exasol/cloudetl/scriptclasses/TableDataExporterTest.scala

#232: Updated dependencies and replaced references to discontinued mavon.exasol.com repository

---

doc/changes/changelog.md
doc/changes/changes_2.7.0.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/main/scala/com/exasol/cloudetl/emitter/FilesDataEmitter.scala
src/main/scala/com/exasol/cloudetl/parquet/RowWriteSupport.scala
src/main/scala/com/exasol/cloudetl/scriptclasses/TableDataExporter.scala
src/main/scala/com/exasol/cloudetl/sink/Sink.scala
src/main/scala/com/exasol/cloudetl/source/Source.scala
src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
src/test/java/com/exasol/cloudetl/extension/ExtensionIT.java
src/test/scala/com/exasol/cloudetl/bucket/DeltaFormatBucketTest.scala
src/test/scala/com/exasol/cloudetl/storage/StoragePropertiesTest.scala

#225: Upgraded common import-export UDF dependency library

---

doc/changes/changelog.md
doc/changes/changes_2.7.1.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/test/java/com/exasol/cloudetl/extension/ExtensionIT.java

#238: Updated `PARALLELISM` information in user guide

---

.github/workflows/ci-build.yml
doc/changes/changelog.md
doc/changes/changes_2.7.2.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/test/java/com/exasol/cloudetl/extension/ExtensionIT.java
src/test/scala/com/exasol/cloudetl/it/BaseIntegrationTest.scala
src/test/scala/com/exasol/cloudetl/it/BaseS3IntegrationTest.scala
src/test/scala/com/exasol/cloudetl/it/alluxio/AlluxioExportImportIT.scala

#243: Removed target file name from `curl` commands in user guide

---

.scalafmt.conf
doc/changes/changes_2.7.2.md
pk_generated_parent.pom
pom.xml

#245: Fixed dependency check vulnerability findings

---

doc/changes/changes_2.7.2.md
pom.xml

#247: Fixed dependency check vulnerability findings

---

.github/workflows/ci-build.yml
doc/changes/changes_2.7.2.md
pom.xml
src/test/scala/com/exasol/cloudetl/it/BaseIntegrationTest.scala

#253: Upgraded dependency versions

---

doc/changes/changes_2.7.2.md
doc/user_guide/user_guide.md

#250: Added `S3_ENDPOINT_REGION` parameter description

---

.gitattributes
.github/workflows/ci-build.yml
.gitignore
.project-keeper.yml
dependencies.md
doc/changes/changelog.md
doc/changes/changes_2.7.6.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml
src/test/java/com/exasol/cloudetl/extension/ExtensionIT.java
src/test/scala/com/exasol/cloudetl/it/BaseIntegrationTest.scala

Fixed vulnerabilities CVE-2023-44981 and CVE-2023-46120

---

dependencies.md
doc/changes/changelog.md
doc/changes/changes_2.7.9.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml

#288: Fix CVE-2023-6378

---

.github/workflows/release_droid_prepare_original_checksum.yml

Free space

---

.github/workflows/dependencies_update.yml
dependencies.md
doc/changes/changelog.md
doc/changes/changes_2.8.1.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml

#318: CVE-2024-36114: io.airlift:aircompressor:jar:0.25:compile

---

.github/workflows/ci-build.yml
.github/workflows/dependencies_update.yml
.project-keeper.yml
dependencies.md
doc/changes/changelog.md
doc/changes/changes_2.8.2.md
doc/user_guide/user_guide.md
pk_generated_parent.pom
pom.xml

#322 Upgrade dependencies
