- .travis.yml
Previously it was generated using `travis encrypt 'GITHUB_TOKEN=token'` command.
> Use only `travis encrypt <oauth-key>`

- project/Dependencies.scala
- project/plugins.sbt
- scripts/ci.sh
With each build it will show unused (also undeclared) dependencies.
> Add explicit-dependencies sbt plugin

- README.md
- src/main/scala/com/exasol/cloudetl/scriptclasses/ImportS3Files.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/ImportS3Metadata.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/ImportS3Path.scala
This will allow to use user defined S3 bucket endpoint instead of hardcoded Frankfurt
(eu-central-1) region.
> Parameterize S3 endpoint

- .travis.yml
- build.sbt
- project/Dependencies.scala
- sbtx
- scripts/ci.sh
> Update Hadoop, Exasol JDBC and Scala versions

- src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
- src/main/scala/com/exasol/cloudetl/kafka/KafkaConsumerProperties.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/KafkaImport.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/KafkaMetadata.scala
It adds additional user parameters when using udf to import from Kafka clusters. Additionally, improves the Kafka consumer application code.
Thanks Hari for your feedback and contributions!
Fixes #41.
> Apply patch from Hari Nair (CommScope)

- docs/overview.md
- src/main/scala/com/exasol/cloudetl/bucket/AzureBlobBucket.scala
- src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
It makes it possible to use Azure Blob Store container SAS token when importing or exporting data to/from Exasol table. This is additional feature to previous Account Secret Key access usage.
Fixes #42.
> Support SAS Token to access Azure Blob Storage

- src/main/scala/com/exasol/cloudetl/parquet/RowReadSupport.scala
- src/main/scala/com/exasol/cloudetl/util/DateTimeUtil.scala
- src/test/scala/com/exasol/cloudetl/parquet/ParquetRowReaderTest.scala
> Fix Parquet import timestamps encoded as milliseconds since epoch.

- src/main/scala/com/exasol/cloudetl/bucket/AzureBlobBucket.scala
- src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
- src/test/scala/com/exasol/cloudetl/bucket/AzureBlobBucketTest.scala
- src/test/scala/com/exasol/cloudetl/storage/StoragePropertiesTest.scala
This will not enforce users to explicitly provide `AZURE_ACCOUNT_NAME` and `AZURE_CONTAINER_NAME` properties when accessing Azure Blob Storage. 
Since those two values are available in the provided path, we obtain them from it.
> Obtain account and container names from provided path in Azure Blob Storage.

- src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
- src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
- src/test/scala/com/exasol/cloudetl/storage/StoragePropertiesTest.scala
The `java.net.URI` cannot resolve the paths that contain regex patterns,
for example, `'s3a://bucket/{year=2019/month=1,year=2019/month=2}/*'`.
Instead we should use Hadoop Filesystem Path, and then convert the path
to URI using `.toUri()` method.
For example, to obtain the schema from a path:
```scala
new Path(bucketPathString).toUri.getSchema
```
> Use Hadoop Filesystem Path URI instead of java.net.URI

- README.md
- docs/kafka/import.md
- docs/storage/delta_format.md
- project/Dependencies.scala
- project/Settings.scala
- src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
- src/main/scala/com/exasol/cloudetl/source/Source.scala
- src/main/scala/com/exasol/cloudetl/storage/FileFormat.scala
- src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
- src/test/scala/com/exasol/cloudetl/bucket/AbstractBucketTest.scala
- src/test/scala/com/exasol/cloudetl/bucket/DeltaFormatBucketTest.scala
- src/test/scala/com/exasol/cloudetl/data/RowTest.scala
- src/test/scala/com/exasol/cloudetl/storage/FileFormatTest.scala
- src/test/scala/com/exasol/cloudetl/storage/StoragePropertiesTest.scala
> Adds Delta format import integration

- docs/user_guide.md
- src/main/scala/com/exasol/cloudetl/scriptclasses/ExportPath.scala
- src/main/scala/com/exasol/cloudetl/storage/StorageProperties.scala
- src/test/scala/com/exasol/cloudetl/scriptclasses/ExportPathTest.scala
- src/test/scala/com/exasol/cloudetl/storage/StoragePropertiesTest.scala
If this parameter is set to `true`, deletes the files inside the export path before starting the export process.
> Adds `OVERWRITE` parameter for the EXPORT UDF.

- src/main/scala/com/exasol/cloudetl/sink/BatchSizedSink.scala
- src/test/scala/com/exasol/cloudetl/scriptclasses/ExportTableTest.scala
> Adds compression codec as extension to exported files.

- src/it/scala/com/exasol/cloudetl/kafka/KafkaConsumerPropertiesIT.scala
- src/main/scala/com/exasol/cloudetl/kafka/KafkaConnectorException.scala
- src/main/scala/com/exasol/cloudetl/kafka/KafkaConsumerProperties.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/KafkaImport.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/KafkaMetadata.scala
- src/test/scala/com/exasol/cloudetl/kafka/KafkaConsumerPropertiesTest.scala
We're looking to work with the cloud ETL support for Kafka, and a clear requirement for us would be to use connection objects, both for enabling access for analysts / data scientists without exposing credentials, and to avoid seeing credentials everywhere in the logs.
I've done my best to implement Kafka support for connection objects similar to how it's done for Kinesis, but I'm very much open to suggestions on changes needed as I don't really have any experience with Scala.
> Add support for using connection objects with Kafka

- src/main/scala/com/exasol/cloudetl/kafka/KafkaConsumerProperties.scala
To avoid getting a confusing error deeper in the stack that surfaces to the Exasol query result, check to make sure that the keystore and truststore files actually exist while validating the Kafka client. This allows us to show a more understandable message that can be acted on directly.
> Add checks for existing keystore and truststore files when creating Kafka client

- .github/workflows/ci-build.yml
- build.sbt
- doc/changes/changelog.md
- doc/changes/changes_1.3.1.md
- project/Dependencies.scala
- project/plugins.sbt
- project/project/plugins.sbt
- scripts/ci.sh
- src/it/scala/com/exasol/cloudetl/BaseIntegrationTest.scala
- src/it/scala/com/exasol/cloudetl/BaseS3IntegrationTest.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/TableDataExporter.scala
- src/main/scala/com/exasol/cloudetl/sink/BatchSizedSink.scala
- src/test/scala/com/exasol/cloudetl/scriptclasses/TableDataExporterTest.scala
> #168: Return exported records count after export

- .github/workflows/ci-build.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- build.sbt
- doc/changes/changelog.md
- doc/changes/changes_2.3.0.md
- doc/user_guide/user_guide.md
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
- project/project/plugins.sbt
- src/it/scala/com/exasol/cloudetl/BaseIntegrationTest.scala
- src/it/scala/com/exasol/cloudetl/alluxio/AlluxioExportImportIT.scala
- src/it/scala/com/exasol/cloudetl/parquet/ParquetDataImporterIT.scala
- src/main/scala/com/exasol/cloudetl/bucket/Bucket.scala
- src/test/scala/com/exasol/cloudetl/parquet/ParquetRowReaderPrimitiveTypesTest.scala
> #181: Added support for reading Parquet `INT64` with `TIMESTAMP_MICROS` logical type

- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/release_droid_prepare_original_checksum.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- doc/changes/changes_2.7.4.md
- src/test/scala/com/exasol/cloudetl/it/BaseIntegrationTest.scala
Fixes: https://github.com/exasol/cloud-storage-extension/issues/275
> Fix for release issue

- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.7.4.md
- doc/changes/changes_2.7.5.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/scala/com/exasol/cloudetl/emitter/FilesDataEmitter.scala
- src/main/scala/com/exasol/cloudetl/scriptclasses/FilesDataImporter.scala
- src/test/java/com/exasol/cloudetl/scriptclasses/ExaIteratorMock.java
- src/test/java/org/apache/log4j/MDC.java
- src/test/java/org/apache/log4j/helpers/ThreadLocalMap.java
- src/test/scala/com/exasol/cloudetl/DataRecords.scala
- src/test/scala/com/exasol/cloudetl/it/BaseDataImporter.scala
- src/test/scala/com/exasol/cloudetl/it/BaseIntegrationTest.scala
- src/test/scala/com/exasol/cloudetl/it/BaseS3IntegrationTest.scala
- src/test/scala/com/exasol/cloudetl/it/avro/AvroDataImporterIT.scala
- src/test/scala/com/exasol/cloudetl/it/orc/OrcDataImporterIT.scala
- src/test/scala/com/exasol/cloudetl/it/parquet/ParquetDataImporterIT.scala
- src/test/scala/com/exasol/cloudetl/scriptclasses/FilesDataImporterTest.scala
- src/test/scala/com/exasol/cloudetl/scriptclasses/TableDataExporterTest.scala
- src/test/scala/com/exasol/cloudetl/transform/DefaultTransformationTest.scala
> #280: Improve log messages for import

- .github/workflows/ci-build.yml
- .github/workflows/dependencies_check.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.7.7.md
- doc/user_guide/user_guide.md
- extension/package-lock.json
- extension/package.json
- extension/src/extension.test.ts
- extension/src/extension.ts
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/cloudetl/extension/ExtensionIT.java
- src/test/scala/com/exasol/cloudetl/it/BaseIntegrationTest.scala
> #284: Use shared extension integration tests

- doc/changes/changelog.md
- doc/changes/changes_2.7.11.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
> Upgrade zookeeper
